services:
  mysql-m:
    image: mysql:8.4
    container_name: mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_USER: marcus
      MYSQL_PASSWORD: marcus
    ports:
      - "3306:3306"
    volumes:
      - mysql_master_data:/var/lib/mysql
      - ./configs/master.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mysql_replication
  
  mysql-s1:
    image: mysql:8.4
    container_name: mysql_s1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_USER: marcus
      MYSQL_PASSWORD: marcus
    ports:
      - "3307:3306"
    volumes:
      - mysql_s1_data:/var/lib/mysql
      - ./configs/slave1.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mysql_replication

  mysql-s2:
    image: mysql:8.4
    container_name: mysql_s2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_USER: marcus
      MYSQL_PASSWORD: marcus
    ports:
      - "3308:3306"
    volumes:
      - mysql_s2_data:/var/lib/mysql
      - ./configs/slave2.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mysql_replication
  
volumes:
  mysql_master_data:
  mysql_s1_data:
  mysql_s2_data:
  
networks:
  mysql_replication:
    driver: bridge
