CHANGE REPLICATION SOURCE TO SOURCE_HOST='mysql_master',
SOURCE_USER='slave',
SOURCE_PASSWORD='slavepass',
SOURCE_LOG_FILE='mysql-bin.000001',
SOURCE_LOG_POS=158;

START REPLICA;

SHOW REPLICA STATUS\G;